### PR TITLE
Update to ENTT v3.10.1

### PR DESCRIPTION
**Pull request by qhdwight**
Mainly just updating the context API

### CODE REVIEW

**Comment by qhdwight** [comment]
This is proving harder than I thought, getting some weird compiler errors relating to `visit_component` in shapes:

```
C:\<path>\pkg\edyn\include\edyn/shapes/shapes.hpp(100): error C2672: 'visit_component': no matching overloaded function found
C:\<path>\pkg\edyn\src\edyn\collision\raycast.cpp(44): note: see reference to function template instantiation 'void edyn::visit_shape<edyn::raycast::<lambda_1>::()::<lambda_1>>(const edyn::shape_index &,entt::entity,const edyn::tuple_of_shape_views_t &,VisitorType)' being compiled
        with
        [
            VisitorType=edyn::raycast::<lambda_1>::()::<lambda_1>
        ]
C:\<path>\pkg\edyn\include\edyn/shapes/shapes.hpp(100): error C2440: 'initializing': cannot convert from 'const edyn::tuple_of_shape_views_t' to 'entt::registry &'
C:\<path>\pkg\edyn\include\edyn/shapes/shapes.hpp(99): error C2780: 'void edyn::visit_component(IndexType,entt::entity,entt::registry &,VisitorType)': expects 4 arguments - 5 provided
C:\<path>\pkg\edyn\include\edyn/util/visit_component.hpp(129): note: see declaration of 'edyn::visit_component'
C:\<path>\pkg\edyn\include\edyn/shapes/shapes.hpp(99): error C2782: 'void edyn::visit_component(std::tuple<_Types...>,IndexType,entt::entity,const std::tuple<entt::basic_view<entt::entity,entt::type_list<Type...>,entt::type_list<>,void>...> &,VisitorType)': template parameter 'Ts' is ambiguous
C:\<path>\pkg\edyn\include\edyn/util/visit_component.hpp(78): note: see declaration of 'edyn::visit_component'
C:\<path>\pkg\edyn\include\edyn/shapes/shapes.hpp(99): note: could be 'edyn::sphere_shape, edyn::cylinder_shape, edyn::capsule_shape, edyn::box_shape, edyn::polyhedron_shape, edyn::compound_shape, edyn::plane_shape, edyn::mesh_shape, edyn::paged_mesh_shape'
C:\<path>\pkg\edyn\include\edyn/shapes/shapes.hpp(99): note: or       'edyn::sphere_shape'
C:\<path>\pkg\edyn\include\edyn/shapes/shapes.hpp(99): error C2784: 'void edyn::visit_component(std::tuple<_Types...>,IndexType,entt::entity,const std::tuple<entt::basic_view<entt::entity,entt::type_list<Type...>,entt::type_list<>,void>...> &,VisitorType)': could not deduce template argument for 'const std::tuple<entt::basic_view<entt::entity,entt::type_list<Type...>,entt::type_list<>,void>...> &' from 'const edyn::tuple_of_shape_views_t'
C:\<path>\pkg\edyn\include\edyn/util/visit_component.hpp(78): note: see declaration of 'edyn::visit_component'
C:\<path>\pkg\edyn\include\edyn/shapes/shapes.hpp(99): error C2780: 'void edyn::visit_component(IndexType,entt::entity,const std::tuple<entt::basic_view<entt::entity,entt::type_list<Type...>,entt::type_list<>,void>...> &,VisitorType)': expects 4 arguments - 5 provided
C:\<path>\pkg\edyn\include\edyn/util/visit_component.hpp(67): note: see declaration of 'edyn::visit_component'
```

**Comment by xissburg** [comment]
Looks like an issue with the  MSVC compiler. It seems it finds the definition of `visit_component` to be ambiguous, because of the parameter pack apparently.

**Comment by qhdwight** [comment]
Same issue with Apple Clang as well. I can test on GCC as well.

**Comment by xissburg** [comment]
I have compiled it in the Mac as well, never had this problem. Check what version of clang you're using.

**Comment by qhdwight** [comment]
```
❯ clang -v
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: arm64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
Compile error:
```
FAILED: /<path>/build/edyn/CMakeFiles/Edyn.dir/src/edyn/collision/raycast.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -I/<path>/q-engine/src/../pkg/imgui -I/<path>/q-engine/src/../pkg/entt/src -I/<path>/q-engine/pkg/edyn/include -I/<path>/build/edyn/include -I/<path>/q-engine/pkg/entt/src -O2 -g -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Wall -Wno-reorder -Wno-long-long -Wimplicit-fallthrough -std=gnu++2a -MD -MT /<path>/build/edyn/CMakeFiles/Edyn.dir/src/edyn/collision/raycast.cpp.o -MF /<path>/build/edyn/CMakeFiles/Edyn.dir/src/edyn/collision/raycast.cpp.o.d -o /<path>/build/edyn/CMakeFiles/Edyn.dir/src/edyn/collision/raycast.cpp.o -c /<path>/q-engine/pkg/edyn/src/edyn/collision/raycast.cpp
In file included from /<path>/q-engine/pkg/edyn/src/edyn/collision/raycast.cpp:13:
/<path>/q-engine/pkg/edyn/include/edyn/shapes/shapes.hpp:100:5: error: no matching function for call to 'visit_component'
    visit_component(shapes_tuple, index.value, entity, views_tuple, visitor);
    ^~~~~~~~~~~~~~~
/<path>/q-engine/pkg/edyn/src/edyn/collision/raycast.cpp:36:9: note: in instantiation of function template specialization 'edyn::visit_shape<(lambda at /<path>/q-engine/pkg/edyn/src/edyn/collision/raycast.cpp:36:56)>' requested here
        visit_shape(sh_idx, entity, shape_views_tuple, [&](auto &&shape) {
        ^
/<path>/q-engine/pkg/edyn/include/edyn/util/visit_component.hpp:139:6: note: candidate function template not viable: no known conversion from 'const edyn::tuple_of_shape_views_t' (aka 'const tuple<basic_view<entt::entity, type_list<edyn::sphere_shape>, type_list<>>, basic_view<entt::entity, type_list<edyn::cylinder_shape>, type_list<>>, basic_view<entt::entity, type_list<edyn::capsule_shape>, type_list<>>, basic_view<entt::entity, type_list<edyn::box_shape>, type_list<>>, basic_view<entt::entity, type_list<edyn::polyhedron_shape>, type_list<>>, basic_view<entt::entity, type_list<edyn::compound_shape>, type_list<>>, basic_view<entt::entity, type_list<edyn::plane_shape>, type_list<>>, basic_view<entt::entity, type_list<edyn::mesh_shape>, type_list<>>, basic_view<entt::entity, type_list<edyn::paged_mesh_shape>, type_list<>>>') to 'entt::registry &' (aka 'basic_registry<entt::entity> &') for 4th argument
void visit_component(std::tuple<Ts...>, IndexType index, entt::entity entity,
     ^
/<path>/q-engine/pkg/edyn/include/edyn/util/visit_component.hpp:78:6: note: candidate template ignored: deduced packs of different lengths for parameter 'Ts' (<edyn::sphere_shape, edyn::cylinder_shape, edyn::capsule_shape, edyn::box_shape, edyn::polyhedron_shape, edyn::compound_shape, edyn::plane_shape, edyn::mesh_shape, edyn::paged_mesh_shape> vs. <edyn::sphere_shape>)
void visit_component(std::tuple<Ts...>, IndexType index, entt::entity entity,
     ^
/<path>/q-engine/pkg/edyn/include/edyn/util/visit_component.hpp:67:6: note: candidate function template not viable: requires 4 arguments, but 5 were provided
void visit_component(IndexType index, entt::entity entity,
     ^
/<path>/q-engine/pkg/edyn/include/edyn/util/visit_component.hpp:129:6: note: candidate function template not viable: requires 4 arguments, but 5 were provided
void visit_component(IndexType index, entt::entity entity,
     ^
1 error generated.
```

**Comment by qhdwight** [comment]
I can solve it by doing this:
```c++
template<typename VisitorType>
void visit_shape(const shape_index &index, entt::entity entity,
                 const tuple_of_shape_views_t &views_tuple, VisitorType visitor) {
    visit_component<edyn::sphere_shape, edyn::cylinder_shape, edyn::capsule_shape, edyn::box_shape, edyn::polyhedron_shape, edyn::compound_shape, edyn::plane_shape, edyn::mesh_shape, edyn::paged_mesh_shape>(shapes_tuple, index.value, entity, views_tuple, visitor);
}
```
But that is disgusting and not robust

**Comment by qhdwight** [comment]
Seems to work afaik

**Comment by xissburg** [comment]
Perhaps the non-tuple version of `visit_component` could be removed because it's not used.

**Pull request merged**
