### PR TITLE
Cleaned up CMakeLists.txt

### PR DESCRIPTION
**Pull request by StellaSmith**
Sadly i couldn't build the tests due to lacking the GMock library

Make building tests and examples default to off if this is the top most project
Use generator cmake_find_package and cmake_paths to allow simply using find_package
Use generator expressions where applicable

### CODE REVIEW

**Comment by xissburg** [comment]
Thanks for the contribution! The CMake files often don't get a lot of love. However, there are a couple of issues:
- The `ENTT_DISABLE_ASSERT` option has been removed.
- I am getting the error "[build] clang: error: no such file or directory: 'EDYN_DEBUG'". It looks like `target_compile_definitions` should be used instead of  `target_compile_options`.
- The address sanitizer flags have been removed. Yes, they were commented out which was a lazy move on my part. They could be moved into a CMake option as well.

**Comment by StellaSmith** [comment]
I'm going to work on those changes late today then.

**Comment by xissburg** [comment]
Cool, thanks 🙂By the way, I think we could add google-test/gtest via Conan as well 🤔

**Comment by StellaSmith** [comment]
I don't think adding gtest in the conan requirements would be useful, since most projects don't enable testing for their required libraries. Instead i think the best option would be having the people working on this project install the library into their system manually.

That being said, i tried installed gtest in arch, and cmake didn't find the gmock libraries, so i think the names used where either wrong or outdated. I've never used gtest so i can't say for sure.

**Comment by StellaSmith** [comment]
I think the way it is now is good, let me know if i missed something.

**Comment by StellaSmith** [comment]
Also sorry for all the typos in the commit messages.

**Comment by xissburg** [comment]
`ENTT_DISABLE_ASSERT` is actually an EnTT setting (https://github.com/skypjack/entt/wiki/Crash-Course:-configuration#entt_disable_assert), it wasn't a typo :) That's useful if you want to compile Edyn in debug mode without EnTT assertions which can significantly slowdown bigger simulations.

**Comment by StellaSmith** [comment]
Yes, but i don't thing having this project take control of that option would be nice.

**Comment by xissburg** [comment]
This is a compiled library, which means compiling without `ENTT_DISABLE_ASSERT` set, will result in EnTT asserts being compiled into the binary. If you compile with `ENTT_DISABLE_ASSERT` enabled, it's going to run faster in debug mode, which is useful sometimes to speed up bigger simulations significantly. I often enable and disable this setting depending on what I am working on. It's more of a developer utility. People who know what `ENTT_DISABLE_ASSERT` is will thank us for having this option :P

**Comment by StellaSmith** [comment]
If that's the case, then setting `EDYN_DISABLE_ASSERT` will define `ENTT_DISABLE_ASSERT` only in the source files of Edyn.
Just let me finish my classes and i will change it.

**Comment by StellaSmith** [comment]
That should do it

**Comment by xissburg** [comment]
Looks great! Thank you!

**Pull request merged**
